//! The three things a merge has to be, whatever it is handed.
//!
//! Idempotent: reading the same file twice is not two edits. Commutative: which
//! file arrived first cannot decide the answer. Convergent: two devices that
//! exchange what they wrote end up holding the same notes. Nothing above these
//! is worth much — a merge that loses one of them loses data on a schedule
//! nobody can predict.
//!
//! The documents are generated by mutating one shared base, because two
//! independently generated documents share no ids and would never collide at
//! all. Stamps come from a deliberately narrow range so near-misses are common
//! rather than rare.

use notes_sync::document::{
    DocumentId, DocumentNode, DocumentRoot, Marker, NodeBody, PageDocument, VaultFile,
};
use notes_sync::hlc::{Clock, Hlc};
use notes_sync::merger::{MergeInput, merge_document};
use proptest::prelude::*;
use rusqlite::Connection;

/// Every column of one row, in the order the query names them. A tuple this
/// wide says nothing about what it holds when it is written out inline.
type Row = (
    String,
    String,
    i64,
    String,
    String,
    String,
    String,
    i64,
    i64,
    i64,
    i64,
    i64,
    String,
    String,
);

/// The device the database belongs to. Generated stamps never carry it: a stamp
/// this device issued means a hand edit, which is deliberately order-dependent
/// (it is an edit, after all) and belongs in a unit test rather than here.
const HOME: &str = "cccccccc";
const PAGE_ID: &str = "PrJects00001";

fn database() -> Connection {
    let connection = Connection::open_in_memory().expect("open");
    connection
        .execute_batch(include_str!("../../notes-sqlite/src/schema.sql"))
        .expect("schema");
    connection
        .execute(
            "INSERT INTO sync_meta(singleton, device_id, vault_uuid) VALUES (1, ?1, ?2)",
            (HOME, "3f2a1c8e-0000-4c91-8d02-000000000000"),
        )
        .expect("sync meta");
    notes_sync::hlc::register(&connection, std::sync::Arc::new(clock())).expect("register");
    connection
        .execute(
            "INSERT INTO notes_nodes(id, parent_id, sort_key, kind, text, hlc)
             VALUES ('root', NULL, 0, 'page', 'Home', ?1)",
            [stamp(1, "a3f2a3f2")],
        )
        .expect("root");
    connection
}

fn clock() -> Clock {
    Clock::new(HOME).expect("clock")
}

fn stamp(millis: u64, device: &str) -> String {
    Hlc::new(millis, 0, device).expect("hlc").encode()
}

fn input() -> MergeInput {
    MergeInput {
        file_path: "Projects-PrJects00001/README.md".to_owned(),
        file_hash: "a".repeat(64),
        file_mtime_ms: Some(1_700_000_000_000),
        file_size: Some(256),
    }
}

fn merge(connection: &mut Connection, file: &VaultFile) -> usize {
    let transaction = connection.transaction().expect("begin");
    let applied = merge_document(&transaction, &clock(), file, &input(), None)
        .expect("merge")
        .applied;
    transaction.commit().expect("commit");
    applied
}

/// Everything the merge is answerable for, and nothing it is not. Sort keys
/// become sibling ranks — the exact key depends on the history of moves, while
/// the order is the contract. Stamps the merge issued itself become a sentinel:
/// which bytes a fresh stamp carries differs per device by design, so the
/// contract is *which* nodes got one, asserted separately.
fn dump(connection: &Connection, known_stamps: &[String]) -> Vec<String> {
    let mut statement = connection
        .prepare(
            "SELECT id, parent_id, sort_key, kind, text, note, marker, ordered_start,
                    collapsed, completed, starred, deleted, hlc, sync_extras
             FROM notes_nodes ORDER BY parent_id, sort_key, id",
        )
        .expect("prepare");
    let rows: Vec<Row> = statement
        .query_map([], |row| {
            Ok((
                row.get(0)?,
                row.get::<_, Option<String>>(1)?.unwrap_or_default(),
                row.get(2)?,
                row.get(3)?,
                row.get(4)?,
                row.get(5)?,
                row.get(6)?,
                row.get(7)?,
                row.get(8)?,
                row.get(9)?,
                row.get(10)?,
                row.get(11)?,
                row.get(12)?,
                row.get(13)?,
            ))
        })
        .expect("query")
        .map(|row| row.expect("row"))
        .collect();

    let mut rank = std::collections::BTreeMap::new();
    let mut out = Vec::new();
    for row in &rows {
        let next = rank.entry(row.1.clone()).or_insert(0);
        *next += 1;
        let stamp = if known_stamps.contains(&row.12) || row.12.is_empty() {
            row.12.clone()
        } else {
            "fresh".to_owned()
        };
        out.push(format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}",
            row.0,
            row.1,
            next,
            row.3,
            row.4,
            row.5,
            row.6,
            row.7,
            row.8,
            row.9,
            row.10,
            row.11,
            stamp,
            row.13
        ));
    }
    out
}

fn node_id(index: usize) -> String {
    format!("Nd{index:010}")
}

/// A document every node of which carries an id and a stamp. Idempotence is
/// promised for these — a file still missing ids has values to issue, and
/// issuing them is a change by definition.
fn canonical_document() -> impl Strategy<Value = PageDocument> {
    (1usize..=8, prop::collection::vec(0u64..12, 8), 0u64..12).prop_map(
        |(count, millis, root_millis)| {
            let nodes: Vec<DocumentNode> = (0..count)
                .map(|index| DocumentNode {
                    id: node_id(index + 1),
                    hlc: stamp(millis[index], "a3f2a3f2"),
                    body: NodeBody::Text(format!("node {index}")),
                    note: String::new(),
                    marker: Marker::Bullet,
                    collapsed: false,
                    completed: false,
                    starred: false,
                    from: None,
                    place: None,
                    unknown_tokens: Vec::new(),
                    children: Vec::new(),
                })
                .collect();
            let max = nodes
                .iter()
                .map(|node| node.hlc.clone())
                .max()
                .unwrap_or_default()
                .max(stamp(root_millis, "a3f2a3f2"));
            PageDocument {
                id: DocumentId::Node(PAGE_ID.to_owned()),
                parent: None,
                sort_key: None,
                max_hlc: max.clone(),
                // Built in memory, so there is no file that could have been cut short.
                stated_max_hlc: max,
                root: DocumentRoot {
                    title: "Projects".to_owned(),
                    hlc: stamp(root_millis, "a3f2a3f2"),
                    ..DocumentRoot::default()
                },
                nodes,
                unknown_frontmatter: Vec::new(),
                writer: None,
            }
        },
    )
}

/// What one device did to the shared base. `device` is the stamp it signs its
/// own edits with, so the two versions collide on the same ids at close times.
#[derive(Clone, Debug)]
enum Change {
    Retext {
        at: usize,
        millis: u64,
    },
    Restamp {
        at: usize,
        millis: u64,
    },
    MoveToFront {
        at: usize,
        millis: u64,
    },
    /// An edit nobody restamped — a person in another editor.
    HandEdit {
        at: usize,
    },
}

fn changes() -> impl Strategy<Value = Vec<Change>> {
    prop::collection::vec(
        prop_oneof![
            (0usize..8, 0u64..12).prop_map(|(at, millis)| Change::Retext { at, millis }),
            (0usize..8, 0u64..12).prop_map(|(at, millis)| Change::Restamp { at, millis }),
            (0usize..8, 0u64..12).prop_map(|(at, millis)| Change::MoveToFront { at, millis }),
            (0usize..8).prop_map(|at| Change::HandEdit { at }),
        ],
        0..6,
    )
}

fn apply_changes(base: &PageDocument, changes: &[Change], device: &str) -> PageDocument {
    let mut document = base.clone();
    for change in changes {
        let count = document.nodes.len();
        if count == 0 {
            break;
        }
        match change {
            Change::Retext { at, millis } => {
                let at = at % count;
                document.nodes[at].body = NodeBody::Text(format!("edited by {device} {millis}"));
                document.nodes[at].hlc = stamp(*millis, device);
            }
            Change::Restamp { at, millis } => {
                let at = at % count;
                document.nodes[at].hlc = stamp(*millis, device);
            }
            Change::MoveToFront { at, millis } => {
                let at = at % count;
                let mark = stamp(*millis, device);
                // A move rewrites three claims: the node itself, whoever it now
                // follows, and whoever it stopped following. Anything less and
                // the file states an order nobody claimed.
                let orphaned_follower = document.nodes.get(at + 1).map(|node| node.id.clone());
                let left_behind = if at == 0 {
                    String::new()
                } else {
                    document.nodes[at - 1].id.clone()
                };
                let mut moved = document.nodes.remove(at);
                if let Some(follower) = orphaned_follower
                    && let Some(node) = document.nodes.iter_mut().find(|node| node.id == follower)
                {
                    node.place = Some((left_behind, mark.clone()));
                }
                if let Some(displaced) = document.nodes.first_mut() {
                    displaced.place = Some((moved.id.clone(), mark.clone()));
                }
                moved.hlc = mark.clone();
                moved.place = Some((String::new(), mark.clone()));
                document.nodes.insert(0, moved);
            }
            Change::HandEdit { at } => {
                let at = at % count;
                // The stamp stays exactly as it was, which is what a person
                // editing the file in another editor leaves behind. Only a
                // stamp this device never issued may be hand-edited here: its
                // own stamp means authoring, which is order-dependent on
                // purpose and belongs in a unit test.
                document.nodes[at].body =
                    NodeBody::Text(format!("hand edited {}", document.nodes[at].id));
            }
        }
    }
    document.max_hlc = document
        .nodes
        .iter()
        .map(|node| node.hlc.clone())
        .max()
        .unwrap_or_default()
        .max(document.root.hlc.clone());
    document
}

fn stamps_of(documents: &[&PageDocument]) -> Vec<String> {
    let mut stamps: Vec<String> = documents
        .iter()
        .flat_map(|document| {
            std::iter::once(document.root.hlc.clone())
                .chain(document.nodes.iter().map(|node| node.hlc.clone()))
        })
        .collect();
    stamps.push(stamp(1, "a3f2a3f2"));
    stamps.sort();
    stamps.dedup();
    stamps
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    /// Reading a file the merge has already read is not an edit. If it were,
    /// every watch echo would advance the revision and the exporter would
    /// rewrite the file, which would produce another echo.
    #[test]
    fn prop_merging_the_same_canonical_doc_twice_is_a_noop(base in canonical_document()) {
        let mut connection = database();
        let known = stamps_of(&[&base]);
        let file = VaultFile::Page(base);
        merge(&mut connection, &file);
        let after_first = dump(&connection, &known);

        let applied = merge(&mut connection, &file);

        prop_assert_eq!(applied, 0, "a replay wrote rows");
        prop_assert_eq!(dump(&connection, &known), after_first);
    }


    /// Two devices' files reaching one vault in either order have to leave it
    /// in the same state. Otherwise the answer depends on network timing.
    #[test]
    fn prop_merge_order_of_two_docs_does_not_change_the_state(
        base in canonical_document(),
        first in changes(),
        second in changes(),
    ) {
        let a = apply_changes(&base, &first, "aaa1aaa1");
        let b = apply_changes(&base, &second, "bbb2bbb2");
        let known = stamps_of(&[&base, &a, &b]);

        let mut forwards = database();
        merge(&mut forwards, &VaultFile::Page(a.clone()));
        merge(&mut forwards, &VaultFile::Page(b.clone()));

        let mut backwards = database();
        merge(&mut backwards, &VaultFile::Page(b));
        merge(&mut backwards, &VaultFile::Page(a));

        prop_assert_eq!(
            dump(&forwards, &known),
            dump(&backwards, &known),
            "the order the files arrived in changed the answer"
        );
    }

    /// Two vaults that each saw one file, then swapped, hold the same notes.
    /// This is the property the whole design exists for.
    #[test]
    fn prop_two_dbs_converge_by_exchanging_exports(
        base in canonical_document(),
        first in changes(),
        second in changes(),
    ) {
        let a = apply_changes(&base, &first, "aaa1aaa1");
        let b = apply_changes(&base, &second, "bbb2bbb2");
        let known = stamps_of(&[&base, &a, &b]);

        let mut mine = database();
        merge(&mut mine, &VaultFile::Page(a.clone()));
        let mut theirs = database();
        merge(&mut theirs, &VaultFile::Page(b.clone()));

        merge(&mut mine, &VaultFile::Page(b));
        merge(&mut theirs, &VaultFile::Page(a));

        prop_assert_eq!(
            dump(&mine, &known),
            dump(&theirs, &known),
            "the two vaults disagree about the same notes"
        );
    }
}
