//! The three things a merge has to be, whatever it is handed.
//!
//! Idempotent: reading the same file twice is not two edits. Commutative: which
//! file arrived first cannot decide the answer. Convergent: two devices that
//! exchange what they wrote end up holding the same notes. Nothing above these
//! is worth much — a merge that loses one of them loses data on a schedule
//! nobody can predict.
//!
//! The documents are generated by mutating one shared base, because two
//! independently generated documents share no ids and would never collide at
//! all. Stamps come from a deliberately narrow range so near-misses are common
//! rather than rare.

use notes_sync::document::{
    DocumentId, DocumentNode, DocumentRoot, Marker, NodeBody, PageDocument, VaultFile,
};
use notes_sync::hlc::{Clock, Hlc};
use notes_sync::merger::{MergeInput, merge_document};
use proptest::prelude::*;
use rusqlite::Connection;

/// The device the database belongs to. Generated stamps never carry it: a stamp
/// this device issued means a hand edit, which is deliberately order-dependent
/// (it is an edit, after all) and belongs in a unit test rather than here.
const HOME: &str = "cccc";
const PAGE_ID: &str = "4f1c8e20-a3b7-4c91-8d02-11c8da70b5e1";

fn database() -> Connection {
    let connection = Connection::open_in_memory().expect("open");
    connection
        .execute_batch(include_str!("../../notes-sqlite/src/schema.sql"))
        .expect("schema");
    connection
        .execute(
            "INSERT INTO sync_meta(singleton, device_id, vault_uuid) VALUES (1, ?1, ?2)",
            (HOME, "3f2a1c8e-0000-4c91-8d02-000000000000"),
        )
        .expect("sync meta");
    notes_sync::hlc::register(&connection, std::sync::Arc::new(clock())).expect("register");
    connection
        .execute(
            "INSERT INTO notes_nodes(id, parent_id, sort_key, kind, text, hlc)
             VALUES ('root', NULL, 0, 'page', 'Home', ?1)",
            [stamp(1, "a3f2")],
        )
        .expect("root");
    connection
}

fn clock() -> Clock {
    Clock::new(HOME).expect("clock")
}

fn stamp(millis: u64, device: &str) -> String {
    Hlc::new(millis, 0, device).expect("hlc").encode()
}

fn input() -> MergeInput {
    MergeInput {
        file_path: "Projects-4f1c8e20a3b7/README.md".to_owned(),
        file_hash: "a".repeat(64),
        file_mtime_ms: Some(1_700_000_000_000),
        file_size: Some(256),
    }
}

fn merge(connection: &mut Connection, file: &VaultFile) -> usize {
    let transaction = connection.transaction().expect("begin");
    let applied = merge_document(&transaction, &clock(), file, &input())
        .expect("merge")
        .applied;
    transaction.commit().expect("commit");
    applied
}

/// Everything the merge is answerable for, and nothing it is not. Sort keys
/// become sibling ranks — the exact key depends on the history of moves, while
/// the order is the contract. Stamps the merge issued itself become a sentinel:
/// which bytes a fresh stamp carries differs per device by design, so the
/// contract is *which* nodes got one, asserted separately.
fn dump(connection: &Connection, known_stamps: &[String]) -> Vec<String> {
    let mut statement = connection
        .prepare(
            "SELECT id, parent_id, sort_key, kind, text, note, marker, ordered_start,
                    collapsed, completed, starred, deleted, hlc, sync_extras
             FROM notes_nodes ORDER BY parent_id, sort_key, id",
        )
        .expect("prepare");
    let rows: Vec<(
        String,
        String,
        i64,
        String,
        String,
        String,
        String,
        i64,
        i64,
        i64,
        i64,
        i64,
        String,
        String,
    )> = statement
        .query_map([], |row| {
            Ok((
                row.get(0)?,
                row.get::<_, Option<String>>(1)?.unwrap_or_default(),
                row.get(2)?,
                row.get(3)?,
                row.get(4)?,
                row.get(5)?,
                row.get(6)?,
                row.get(7)?,
                row.get(8)?,
                row.get(9)?,
                row.get(10)?,
                row.get(11)?,
                row.get(12)?,
                row.get(13)?,
            ))
        })
        .expect("query")
        .map(|row| row.expect("row"))
        .collect();

    let mut rank = std::collections::BTreeMap::new();
    let mut out = Vec::new();
    for row in &rows {
        let next = rank.entry(row.1.clone()).or_insert(0);
        *next += 1;
        let stamp = if known_stamps.contains(&row.12) || row.12.is_empty() {
            row.12.clone()
        } else {
            "fresh".to_owned()
        };
        out.push(format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}",
            row.0,
            row.1,
            next,
            row.3,
            row.4,
            row.5,
            row.6,
            row.7,
            row.8,
            row.9,
            row.10,
            row.11,
            stamp,
            row.13
        ));
    }
    out
}

fn freshly_stamped(connection: &Connection, known_stamps: &[String]) -> Vec<String> {
    let mut statement = connection
        .prepare("SELECT id, hlc FROM notes_nodes ORDER BY id")
        .expect("prepare");
    statement
        .query_map([], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })
        .expect("query")
        .map(|row| row.expect("row"))
        .filter(|(_, hlc)| !hlc.is_empty() && !known_stamps.contains(hlc))
        .map(|(id, _)| id)
        .collect()
}

fn node_id(index: usize) -> String {
    format!("8a201f33-0000-4c91-8d02-{index:012}")
}

/// A document every node of which carries an id and a stamp. Idempotence is
/// promised for these — a file still missing ids has values to issue, and
/// issuing them is a change by definition.
fn canonical_document() -> impl Strategy<Value = PageDocument> {
    (1usize..=8, prop::collection::vec(0u64..12, 8), 0u64..12).prop_map(
        |(count, millis, root_millis)| {
            let nodes: Vec<DocumentNode> = (0..count)
                .map(|index| DocumentNode {
                    id: node_id(index + 1),
                    hlc: stamp(millis[index], "a3f2"),
                    body: NodeBody::Text(format!("node {index}")),
                    note: String::new(),
                    marker: Marker::Bullet,
                    collapsed: false,
                    completed: false,
                    starred: false,
                    from: None,
                    unknown_tokens: Vec::new(),
                    children: Vec::new(),
                })
                .collect();
            let max = nodes
                .iter()
                .map(|node| node.hlc.clone())
                .max()
                .unwrap_or_default()
                .max(stamp(root_millis, "a3f2"));
            PageDocument {
                id: DocumentId::Node(PAGE_ID.to_owned()),
                parent: None,
                sort_key: None,
                max_hlc: max,
                root: DocumentRoot {
                    title: "Projects".to_owned(),
                    hlc: stamp(root_millis, "a3f2"),
                    ..DocumentRoot::default()
                },
                nodes,
                unknown_frontmatter: Vec::new(),
            }
        },
    )
}

/// What one device did to the shared base. `device` is the stamp it signs its
/// own edits with, so the two versions collide on the same ids at close times.
#[derive(Clone, Debug)]
enum Change {
    Retext {
        at: usize,
        millis: u64,
    },
    Restamp {
        at: usize,
        millis: u64,
    },
    MoveToFront {
        at: usize,
        millis: u64,
    },
    /// An edit nobody restamped — a person in another editor.
    HandEdit {
        at: usize,
    },
}

fn changes() -> impl Strategy<Value = Vec<Change>> {
    prop::collection::vec(
        prop_oneof![
            (0usize..8, 0u64..12).prop_map(|(at, millis)| Change::Retext { at, millis }),
            (0usize..8, 0u64..12).prop_map(|(at, millis)| Change::Restamp { at, millis }),
            (0usize..8, 0u64..12).prop_map(|(at, millis)| Change::MoveToFront { at, millis }),
            (0usize..8).prop_map(|at| Change::HandEdit { at }),
        ],
        0..6,
    )
}

fn apply_changes(base: &PageDocument, changes: &[Change], device: &str) -> PageDocument {
    let mut document = base.clone();
    for change in changes {
        let count = document.nodes.len();
        if count == 0 {
            break;
        }
        match change {
            Change::Retext { at, millis } => {
                let at = at % count;
                document.nodes[at].body = NodeBody::Text(format!("edited by {device} {millis}"));
                document.nodes[at].hlc = stamp(*millis, device);
            }
            Change::Restamp { at, millis } => {
                let at = at % count;
                document.nodes[at].hlc = stamp(*millis, device);
            }
            Change::MoveToFront { at, millis } => {
                let at = at % count;
                let mut moved = document.nodes.remove(at);
                moved.hlc = stamp(*millis, device);
                document.nodes.insert(0, moved);
            }
            Change::HandEdit { at } => {
                let at = at % count;
                // The stamp stays exactly as it was, which is what a person
                // editing the file in another editor leaves behind. Only a
                // stamp this device never issued may be hand-edited here: its
                // own stamp means authoring, which is order-dependent on
                // purpose and belongs in a unit test.
                document.nodes[at].body =
                    NodeBody::Text(format!("hand edited {}", document.nodes[at].id));
            }
        }
    }
    document.max_hlc = document
        .nodes
        .iter()
        .map(|node| node.hlc.clone())
        .max()
        .unwrap_or_default()
        .max(document.root.hlc.clone());
    document
}

fn stamps_of(documents: &[&PageDocument]) -> Vec<String> {
    let mut stamps: Vec<String> = documents
        .iter()
        .flat_map(|document| {
            std::iter::once(document.root.hlc.clone())
                .chain(document.nodes.iter().map(|node| node.hlc.clone()))
        })
        .collect();
    stamps.push(stamp(1, "a3f2"));
    stamps.sort();
    stamps.dedup();
    stamps
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    /// Reading a file the merge has already read is not an edit. If it were,
    /// every watch echo would advance the revision and the exporter would
    /// rewrite the file, which would produce another echo.
    #[test]
    fn prop_merging_the_same_canonical_doc_twice_is_a_noop(base in canonical_document()) {
        let mut connection = database();
        let known = stamps_of(&[&base]);
        let file = VaultFile::Page(base);
        merge(&mut connection, &file);
        let after_first = dump(&connection, &known);

        let applied = merge(&mut connection, &file);

        prop_assert_eq!(applied, 0, "a replay wrote rows");
        prop_assert_eq!(dump(&connection, &known), after_first);
    }

}

// The other two properties — commutativity and convergence of *order* — are not
// here yet, and deliberately not written in a weakened form that would pass.
// The generator found a case the current design cannot satisfy: a node that
// never moves still records which sibling it follows the first time it is seen,
// and which file was seen first decides that claim. Two vaults then hold the
// same notes in different orders.
//
// The reproducing shape, from the shrunk counterexample:
//
//   base:  [n1, n2, n3], every stamp equal
//   file A: n2 moved to the front and restamped
//   file B: n1 restamped in place, order unchanged
//
//   A then B  ->  n3 claims "after n1"
//   B then A  ->  n3 claims "after n2"
//
// State converges in both orders; only the sequence differs. Settling it needs
// a rule the format does not have yet — see the merge design's open question on
// ordering convergence. Until that lands, `prop_merge_order_of_two_docs_does_
// not_change_the_state` and `prop_two_dbs_converge_by_exchanging_exports` stay
// unwritten rather than narrowed.
