//! The spec's grammar is the renderer's output, byte for byte. Each fixture is
//! the file a stated document state has to produce; if the renderer and the
//! spec ever disagree, one of them is wrong and this says so.

use notes_sync::document::{
    DocumentId, DocumentNode, DocumentRoot, ImageReference, Marker, NodeBody, PageDocument,
    TrashDocument, VaultFile,
};
use notes_sync::render::render;

/// A golden, compared — or rewritten, when a change to the format is the point.
///
/// `UPDATE_FIXTURES=1 cargo test -p notes-sync --test render_goldens` writes what
/// the renderer produces into the four fixtures and passes. Nothing else in the
/// suite changes behaviour, and a run without the variable is the ordinary
/// byte-for-byte comparison — so a fixture can only move when somebody asked for
/// it to, in a diff they then have to read.
///
/// This exists because the alternative is what happened twice already: a format
/// change lands, four fixtures disagree, and they get regenerated by hand from a
/// throwaway test written for the occasion and deleted afterwards. The next
/// change re-invents it. A snapshot library would also do this, but these files
/// are the spec's own goldens — `docs/v2/sync-spec.md` §11 points at them — and
/// they are worth keeping as readable Markdown under their own names rather than
/// moving into a tool's store.
fn golden(name: &str, rendered: Vec<u8>, committed: &str) {
    let rendered = String::from_utf8(rendered).expect("utf-8");
    if std::env::var_os("UPDATE_FIXTURES").is_some() {
        std::fs::write(format!("fixtures/{name}.md"), &rendered).expect("write the fixture");
        return;
    }
    assert_eq!(
        rendered, committed,
        "`{name}.md` no longer matches the renderer. If the format was meant to \
         change, rerun with UPDATE_FIXTURES=1 and read the diff."
    );
}

fn node(id: &str, hlc: &str, text: &str) -> DocumentNode {
    DocumentNode {
        id: id.to_owned(),
        hlc: hlc.to_owned(),
        body: NodeBody::Text(text.to_owned()),
        note: String::new(),
        marker: Marker::Bullet,
        collapsed: false,
        completed: false,
        starred: false,
        from: None,
        place: None,
        unknown_tokens: Vec::new(),
        children: Vec::new(),
    }
}

fn page() -> PageDocument {
    let mut architecture = node("Nd0000000001", "0swkd7qz6-00-a3f2", "아키텍처 다시 그리기");
    let mut boundaries = node("Nd0000000002", "0swkd7qz7-00-a3f2", "크레이트 경계 정리");
    boundaries.marker = Marker::Todo;
    let mut diagram = node("Nd0000000003", "0swkd7qz8-00-a3f2", "");
    diagram.body = NodeBody::Image(ImageReference {
        original_name: "아키텍처.png".to_owned(),
        path: "assets/아키텍처-9f3a1c8e2044.png".to_owned(),
        display_width: 320,
        pixel_width: 1280,
        pixel_height: 720,
        byte_size: 421_904,
    });
    architecture.children = vec![boundaries, diagram];

    let mut tidied = node("Nd0000000004", "0swkd7qz9-00-a3f2", "정리한 것");
    tidied.completed = true;
    tidied.collapsed = true;

    PageDocument {
        id: DocumentId::Node("PrJects00001".to_owned()),
        parent: None,
        sort_key: None,
        max_hlc: "0swkd7qz9-00-a3f2".to_owned(),
        // Built in memory, so there is no file that could have been cut short.
        stated_max_hlc: "0swkd7qz9-00-a3f2".to_owned(),
        root: DocumentRoot {
            title: "Projects".to_owned(),
            note: "이번 분기에 손대는 것만.".to_owned(),
            hlc: "0swkd7qz5-00-a3f2".to_owned(),
            starred: true,
            ..DocumentRoot::default()
        },
        nodes: vec![architecture, tidied],
        unknown_frontmatter: Vec::new(),
    }
}

#[test]
fn a_page_renders_byte_identical_to_its_golden() {
    let rendered = render(&VaultFile::Page(page())).expect("render");

    golden("page", rendered, include_str!("../fixtures/page.md"));
}

#[test]
fn rendering_the_same_state_twice_is_byte_identical() {
    let first = render(&VaultFile::Page(page())).expect("render");
    let second = render(&VaultFile::Page(page())).expect("render");

    assert_eq!(first, second);
}

#[test]
fn the_trash_renders_byte_identical_to_its_golden() {
    let mut old_page = node("Nd0000000005", "0swkd7qza-00-a3f2", "Old page");
    old_page.from = Some(("root".to_owned(), 4_294_967_296));
    let mut deleted = node("Nd0000000006", "0swkd7qzb-00-a3f2", "Deleted");
    deleted.from = Some(("PrJects00001".to_owned(), 8_589_934_592));
    let mut child = node("Nd0000000007", "0swkd7qzc-00-a3f2", "Child");
    child.completed = true;
    deleted.children = vec![child];

    let rendered = render(&VaultFile::Trash(TrashDocument {
        max_hlc: "0swkd7qzc-00-a3f2".to_owned(),
        nodes: vec![old_page, deleted],
    }))
    .expect("render");

    golden("trash", rendered, include_str!("../fixtures/trash.md"));
}

#[test]
fn a_split_document_renders_byte_identical_to_its_golden() {
    let rendered = render(&VaultFile::Page(PageDocument {
        id: DocumentId::Node("Archive00001".to_owned()),
        parent: Some("PrJects00001".to_owned()),
        sort_key: Some(4_294_967_296),
        max_hlc: "0swkd7qze-00-a3f2".to_owned(),
        // Built in memory, so there is no file that could have been cut short.
        stated_max_hlc: "0swkd7qze-00-a3f2".to_owned(),
        root: DocumentRoot {
            title: "2024 아카이브".to_owned(),
            hlc: "0swkd7qzd-00-a3f2".to_owned(),
            ..DocumentRoot::default()
        },
        nodes: vec![node("Nd0000000008", "0swkd7qze-00-a3f2", "3월 회고")],
        unknown_frontmatter: Vec::new(),
    }))
    .expect("render");

    golden("split", rendered, include_str!("../fixtures/split.md"));
}

#[test]
fn the_home_document_renders_byte_identical_to_its_golden() {
    let mut projects = node("PrJects00001", "0swkd7qz5-00-a3f2", "");
    projects.body = NodeBody::Split {
        title: "Projects".to_owned(),
        path: "Projects-PrJects00001/README.md".to_owned(),
    };
    let mut minutes = node("Mnutes000001", "0swkd7qz6-00-a3f2", "");
    minutes.body = NodeBody::Split {
        title: "회의록".to_owned(),
        path: "회의록-Mnutes000001/README.md".to_owned(),
    };

    let rendered = render(&VaultFile::Page(PageDocument {
        id: DocumentId::Home,
        parent: None,
        sort_key: None,
        max_hlc: "0swkd7qz6-00-a3f2".to_owned(),
        // Built in memory, so there is no file that could have been cut short.
        stated_max_hlc: "0swkd7qz6-00-a3f2".to_owned(),
        root: DocumentRoot {
            title: "Home".to_owned(),
            hlc: "0swkd7qz4-00-a3f2".to_owned(),
            ..DocumentRoot::default()
        },
        nodes: vec![projects, minutes],
        unknown_frontmatter: Vec::new(),
    }))
    .expect("render");

    golden("home", rendered, include_str!("../fixtures/home.md"));
}

/// A checkbox is the todo marker's notation and nothing else, so a completed
/// todo must not also say `done` — the reader would see the same fact twice,
/// and a merge would have two places to disagree about one bit.
#[test]
fn a_completed_todo_says_so_with_its_checkbox_alone() {
    let mut errand = node("Nd0000000009", "0swkd7qzf-00-a3f2", "Errand");
    errand.marker = Marker::Todo;
    errand.completed = true;
    let mut plain = node("Nd000000000a", "0swkd7qzg-00-a3f2", "Plain");
    plain.completed = true;

    let (body, footer) = rendered_parts(vec![errand, plain]);

    assert!(
        body[0].starts_with("- [x] Errand <!--"),
        "a completed todo reads once, as a checked box: {}",
        body[0]
    );
    assert!(
        !footer[0].contains(" done"),
        "and the footer does not say the same bit a second time: {}",
        footer[0]
    );
    assert!(
        body[1].starts_with("- Plain <!--") && !body[1].contains(" done"),
        "a completed bullet has no checkbox to draw: {}",
        body[1]
    );
    assert!(
        footer[1].contains(" done"),
        "so its footer line is the one place that carries it: {}",
        footer[1]
    );
}

/// The child document's frontmatter owns a split node's state. Repeating it on
/// the parent's line would give one node two authorities, and then the order
/// the two files merged in would decide the answer.
#[test]
fn a_split_line_carries_no_state_of_its_own() {
    let mut archive = node("Archive00001", "0swkd7qzd-00-a3f2", "");
    archive.body = NodeBody::Split {
        title: "2024 아카이브".to_owned(),
        path: "2024-아카이브-Archive00001/README.md".to_owned(),
    };
    archive.starred = true;
    archive.collapsed = true;
    archive.completed = true;
    archive.marker = Marker::Todo;

    let (body, footer) = rendered_parts(vec![archive]);

    assert_eq!(
        body[0],
        "- [2024 아카이브](2024-아카이브-Archive00001/README.md) <!-- yid: Archive00001 -->"
    );
    assert_eq!(
        footer[0], "yid: Archive00001 t: 0swkd7qzd-00-a3f2 split",
        "the stamp and `split` are the whole of it: the star, the checkbox and the \
         fold the state above set are the child document's to answer"
    );
}

/// A hand editor and `git diff --check` both eat a trailing space, so a key
/// whose value is missing must not be written at all.
#[test]
fn an_unstamped_document_is_reported_rather_than_written() {
    let mut document = page();
    document.max_hlc = String::new();

    assert_eq!(
        render(&VaultFile::Page(document)).expect_err("unstamped"),
        "A rendered document needs max_hlc.",
        "the report has to name what is missing, not call an empty value invalid"
    );
}

/// A1. Punctuation reaches the file as the person typed it. A backslash in front
/// of every full stop and slash is what made these files unpleasant to read and
/// worse to edit — a reader has to mentally strip them, and anyone who fixes a
/// typo by hand has to know to put them back.
///
/// What still earns a backslash is a character that would open a block where it
/// sits, and that is a question about position rather than about the character.
#[test]
fn ordinary_punctuation_reaches_the_file_unescaped() {
    let mut plain = node(
        "Nd0000000001",
        "0swkd7qz6-00-a3f2",
        "Shift+Enter — 설명 입력하기. 자세히는 docs/v2/sync-spec.md 참고 (2026).",
    );
    plain.note = "값이 3.5 이상, 또는 a*b 꼴이면 skip_this_one 처리".to_owned();

    let (body, _) = rendered_parts(vec![plain]);

    assert_eq!(
        body[0],
        "- Shift+Enter — 설명 입력하기. 자세히는 docs/v2/sync-spec.md 참고 (2026). \
         <!-- yid: Nd0000000001 -->"
    );
    assert_eq!(
        body[1], "  > 값이 3.5 이상, 또는 a*b 꼴이면 skip_this_one 처리",
        "a note is prose, and prose is what a reader came for"
    );
}

/// The characters that keep their backslash, and why each one keeps it. Every
/// one of these is a shape this format's own parser would read as something
/// other than text if it were left alone.
#[test]
fn only_what_would_open_a_block_keeps_its_backslash() {
    let cases = [
        (
            "- 나열",
            r"\- 나열",
            "a line starting with a bullet marker is a bullet",
        ),
        (
            "![링크",
            r"\![링크",
            "and one starting with an image is an image",
        ),
        ("# 제목", r"\# 제목", "a heading marker opens a heading"),
        (
            "1. 첫째",
            r"1\. 첫째",
            "so does a number that closes into a list marker",
        ),
        (
            "1.5배",
            "1.5배",
            "but a number that closes into nothing is a number",
        ),
        ("-5도", "-5도", "and a minus that opens nothing is a minus"),
    ];

    for (typed, expected, why) in cases {
        let (body, _) = rendered_parts(vec![node("Nd0000000001", "0swkd7qz6-00-a3f2", typed)]);

        assert_eq!(
            body[0]
                .strip_prefix("- ")
                .expect("a bullet")
                .split(" <!--")
                .next()
                .expect("text"),
            expected,
            "{why}"
        );
    }
}

/// The body lines and the footer entries, apart. A test about *where* a fact is
/// written needs both halves, and the halves are what the format now separates.
fn rendered_parts(nodes: Vec<DocumentNode>) -> (Vec<String>, Vec<String>) {
    let mut document = page();
    document.root.note = String::new();
    document.nodes = nodes;
    let rendered =
        String::from_utf8(render(&VaultFile::Page(document)).expect("render")).expect("utf-8");
    let (body, footer) = rendered
        .split_once("\n\n")
        .expect("body")
        .1
        .split_once("<!-- yonalist\n")
        .expect("footer");
    (
        body.lines()
            .filter(|line| !line.is_empty())
            .map(str::to_owned)
            .collect(),
        footer
            .trim_end()
            .strip_suffix("-->")
            .expect("a closed footer")
            .lines()
            .map(str::to_owned)
            .collect(),
    )
}

/// A2. The body carries one thing per line: which block the line is. Everything
/// the sync needs in order to merge — the stamp, the place claim, the states
/// Markdown has no notation for, a picture's dimensions — moves to one block at
/// the end of the file, where a reader who came for the notes never has to look.
#[test]
fn a_body_line_carries_its_block_id_and_nothing_else() {
    for (name, bytes) in [
        ("page", include_str!("../fixtures/page.md")),
        ("home", include_str!("../fixtures/home.md")),
        ("split", include_str!("../fixtures/split.md")),
        ("trash", include_str!("../fixtures/trash.md")),
    ] {
        let (body, footer) = bytes
            .split_once("\n<!-- yonalist\n")
            .unwrap_or_else(|| panic!("{name} has no footer"));

        for line in body.lines() {
            let Some((_, comment)) = line.split_once("<!--") else {
                continue;
            };
            assert!(
                comment.starts_with(" yid: ") && comment.ends_with(" -->"),
                "{name}: a body line says more than which block it is: {line}"
            );
            assert_eq!(
                comment.split_whitespace().count(),
                3,
                "{name}: the id is the whole comment: {line}"
            );
        }
        for token in [
            " t: ",
            " prev: ",
            " from: ",
            " star",
            " done",
            " collapsed",
            " ordered: ",
            "<!-- ya:",
        ] {
            assert!(
                !body.contains(token),
                "{name}: `{token}` is still in the body"
            );
        }
        assert!(
            footer.trim_end().ends_with("-->"),
            "{name}: the footer is not closed"
        );
    }
}
