// @vitest-environment node

import { beforeAll, describe, expect, it } from "vitest";
import type {
  NoteAttachment,
  NoteNode,
  NotesWorkspace
} from "../../domain/notes";
import { findNoteDateMatches, formatLocalDateIso } from "./noteDates";
import { tokenizeNoteText } from "./noteTokens";
import {
  createNotesHistorySession,
  type NotesHistorySnapshot
} from "./notesHistory";
import { parseNoteSearchQuery } from "./noteSearchQuery";
import { flattenVisibleOutlineRows } from "./outlineTree";
import {
  normalizeWorkspace,
  notesWorkspaceReducer
} from "./notesWorkspaceReducer";
import { resolveRootLifecycleNavigation } from "./useNotesWorkspace";

// The shared setup registers an unconditional localStorage reset. Supply only
// that hook dependency; Node remains DOM-free for every timed workload.
Object.defineProperty(globalThis, "window", {
  configurable: true,
  value: { localStorage: { clear() {} } }
});

/**
 * Run serially with:
 * NOTES_PERF=1 npm test -- src/features/notes/notesExpansion.performance.test.ts
 *   --pool=threads --maxWorkers=1 --no-file-parallelism
 */

const WARMUP_PAIR_COUNT = 3;
const MEASURED_PAIR_COUNT = 3;
const REGRESSION_LIMIT = 1.2;
const HISTORY_SNAPSHOT_LIMIT = 128;
const MIXED_IMAGE_ATTACHMENT_COUNT = 512;
const MIXED_IMAGE_RESIDENCY_LIMIT = 8;
const CALIBRATION_ITERATIONS = 10_000_000;
const performanceSuite =
  process.env.NOTES_PERF === "1" ? describe : describe.skip;

const recordedEnvironment = {
  recordedAt: "2026-07-15",
  node: "v26.4.0",
  platform: "darwin-arm64",
  cpu: "Apple M1 Pro",
  memoryGiB: 32,
  calibrationIterations: CALIBRATION_ITERATIONS,
  sampling:
    "3 warmup pairs + 3 measured paired batches per case; each pair uses the same per-operation average statistic with alternating order and outputs validated only after both timing windows; the gate compares the current median of 3 pair ratios with a recorded median generated by the identical 3-pair method"
} as const;

interface PerformanceStats {
  readonly medianMs: number;
  readonly samplesMs: readonly number[];
}

interface PairedPerformanceStats {
  readonly workload: PerformanceStats;
  readonly calibration: PerformanceStats;
  readonly normalized: PerformanceStats;
}

interface PairedBatchSample {
  readonly workloadMs: number;
  readonly calibrationMs: number;
}

interface TimedWorkloadSample {
  readonly elapsedMs: number;
  readonly output: unknown;
}

interface RepresentativePairedSample extends PairedBatchSample {
  readonly normalizedRatio: number;
}

interface PreparedWorkload {
  readonly run: () => unknown;
  readonly expected: unknown;
}

interface RecordedBaseline {
  readonly pairedRatioMedian: number;
}

interface PerformanceCase {
  readonly label: string;
  readonly scope: string;
  readonly nodeCount: 1_000 | 10_000;
  readonly operationsPerSample: number;
  readonly recordedBaseline: RecordedBaseline;
  readonly prepare: (nodeCount: number) => PreparedWorkload;
}

function summarizeSamples(samplesMs: readonly number[]): PerformanceStats {
  const sortedSamples = [...samplesMs].sort((left, right) => left - right);
  return {
    medianMs: sortedSamples[Math.floor(sortedSamples.length / 2)]!,
    samplesMs
  };
}

function measurePerOperationAverage(
  workload: PreparedWorkload,
  operationsPerSample: number
): TimedWorkloadSample {
  const startedAt = performance.now();
  let output: unknown;
  for (let operation = 0; operation < operationsPerSample; operation += 1) {
    output = workload.run();
  }
  const elapsedMs = (performance.now() - startedAt) / operationsPerSample;
  return { elapsedMs, output };
}

function representativeSample(samplesMs: readonly number[]): number {
  return summarizeSamples(samplesMs).medianMs;
}

function representativePairedSample(
  samples: readonly PairedBatchSample[]
): RepresentativePairedSample {
  return {
    workloadMs: representativeSample(
      samples.map(({ workloadMs }) => workloadMs)
    ),
    calibrationMs: representativeSample(
      samples.map(({ calibrationMs }) => calibrationMs)
    ),
    normalizedRatio: representativeSample(
      samples.map(({ workloadMs, calibrationMs }) =>
        workloadMs / calibrationMs
      )
    )
  };
}

function measurePairedBatch(
  calibration: PreparedWorkload,
  workload: PreparedWorkload,
  operationsPerSample: number,
  workloadFirst: boolean
): PairedBatchSample {
  let workloadSample: TimedWorkloadSample;
  let calibrationSample: TimedWorkloadSample;
  if (workloadFirst) {
    workloadSample = measurePerOperationAverage(
      workload,
      operationsPerSample
    );
    calibrationSample = measurePerOperationAverage(calibration, 1);
  } else {
    calibrationSample = measurePerOperationAverage(calibration, 1);
    workloadSample = measurePerOperationAverage(workload, operationsPerSample);
  }

  expect(workloadSample.output).toEqual(workload.expected);
  expect(calibrationSample.output).toEqual(calibration.expected);
  return {
    workloadMs: workloadSample.elapsedMs,
    calibrationMs: calibrationSample.elapsedMs
  };
}

function measurePairedWorkload(
  workload: PreparedWorkload,
  operationsPerSample = 1
): PairedPerformanceStats {
  const calibration = prepareCalibration();
  for (let index = 0; index < WARMUP_PAIR_COUNT; index += 1) {
    measurePairedBatch(
      calibration,
      workload,
      operationsPerSample,
      index % 2 === 1
    );
  }

  const workloadSamplesMs: number[] = [];
  const calibrationSamplesMs: number[] = [];
  const normalizedSamples: number[] = [];
  for (let index = 0; index < MEASURED_PAIR_COUNT; index += 1) {
    const sample = measurePairedBatch(
      calibration,
      workload,
      operationsPerSample,
      (WARMUP_PAIR_COUNT + index) % 2 === 1
    );
    workloadSamplesMs.push(sample.workloadMs);
    calibrationSamplesMs.push(sample.calibrationMs);
    normalizedSamples.push(sample.workloadMs / sample.calibrationMs);
  }

  return {
    workload: summarizeSamples(workloadSamplesMs),
    calibration: summarizeSamples(calibrationSamplesMs),
    normalized: summarizeSamples(normalizedSamples)
  };
}

function recordedBaseline(pairedRatioMedian: number): RecordedBaseline {
  return { pairedRatioMedian };
}

function normalizedRegressionRatio(
  currentPairedRatioMedian: number,
  baseline: RecordedBaseline
): number {
  return currentPairedRatioMedian / baseline.pairedRatioMedian;
}

function calibrationChecksum(iterations: number): number {
  const blockSize = 1024;
  const fullBlocks = Math.floor(iterations / blockSize);
  const remainder = iterations % blockSize;
  return (
    fullBlocks * ((blockSize - 1) * blockSize / 2) +
    (remainder - 1) * remainder / 2
  );
}

function prepareCalibration(): PreparedWorkload {
  return {
    run: () => {
      let checksum = 0;
      for (let index = 0; index < CALIBRATION_ITERATIONS; index += 1) {
        checksum += index & 1023;
      }
      return checksum;
    },
    expected: calibrationChecksum(CALIBRATION_ITERATIONS)
  };
}

function countResidue(total: number, residue: number, divisor: number): number {
  return total <= residue ? 0 : Math.floor((total - 1 - residue) / divisor) + 1;
}

const fixedTimestamp = "2026-07-12T00:00:00.000Z";

function noteNode(
  index: number,
  parentId: string | null,
  overrides: Partial<NoteNode> = {}
): NoteNode {
  return {
    id: `node-${index}`,
    nodeKind: "text",
    parentId,
    sortKey: index,
    title: `Node ${index}`,
    note: "",
    layoutMode: "bullets",
    isCollapsed: false,
    isStarred: false,
    completedAt: null,
    createdAt: fixedTimestamp,
    updatedAt: fixedTimestamp,
    deletedAt: null,
    archivedAt: null,
    archiveRootId: null,
    ...overrides
  };
}

function noteAttachment(index: number, nodeId: string): NoteAttachment {
  return {
    id: `attachment-${index}`,
    nodeId,
    sortKey: 100,
    relativePath: `assets/attachment-${index}.png`,
    contentHash: `hash-${index}`,
    originalName: `image-${index}.png`,
    mimeType: "image/png",
    byteSize: 4,
    intrinsicWidth: 640,
    intrinsicHeight: 480,
    displayWidth: 320,
    createdAt: fixedTimestamp,
    updatedAt: fixedTimestamp
  };
}

function treeNodes(nodeCount: number): NoteNode[] {
  return Array.from({ length: nodeCount }, (_, index) => {
    const parentIndex = index === 0 ? null : Math.floor((index - 1) / 8);
    return noteNode(
      index,
      parentIndex === null ? null : `node-${parentIndex}`
    );
  });
}

function prepareMixedImageOutlineProjectionBookkeeping(
  nodeCount: number
): PreparedWorkload {
  const attachmentsByNodeId: Record<string, NoteAttachment[]> = {};
  const nodes = treeNodes(nodeCount).map((node, index) => {
    if (index >= MIXED_IMAGE_ATTACHMENT_COUNT) return node;

    const attachment = noteAttachment(index, node.id);
    attachmentsByNodeId[node.id] = [attachment];
    if (index % 2 === 0) return node;

    return {
      ...node,
      nodeKind: "image" as const,
      title: attachment.originalName,
      note: `Image description ${index}`
    };
  });
  const workspace = normalizeWorkspace({ nodes, attachmentsByNodeId });

  return {
    run: () => {
      const rows = flattenVisibleOutlineRows(workspace, null);
      const residentAttachmentIds: string[] = [];
      let createdObjectUrlCount = 0;
      let maxResidentObjectUrlCount = 0;
      let revokedObjectUrlCount = 0;
      let legacyAttachmentCount = 0;
      let imageNodeAttachmentCount = 0;
      let imageByteSizeChecksum = 0;

      for (const row of rows) {
        const node = workspace.nodesById[row.id];
        const attachments = workspace.attachmentsByNodeId[row.id] ?? [];
        if (!node || attachments.length === 0) continue;

        if (node.nodeKind === "image") {
          imageNodeAttachmentCount += attachments.length;
        } else {
          legacyAttachmentCount += attachments.length;
        }

        for (const attachment of attachments) {
          imageByteSizeChecksum += attachment.byteSize;
          const residentIndex = residentAttachmentIds.indexOf(attachment.id);
          if (residentIndex >= 0) {
            residentAttachmentIds.splice(residentIndex, 1);
          } else {
            createdObjectUrlCount += 1;
          }
          residentAttachmentIds.push(attachment.id);
          if (residentAttachmentIds.length > MIXED_IMAGE_RESIDENCY_LIMIT) {
            residentAttachmentIds.shift();
            revokedObjectUrlCount += 1;
          }
          maxResidentObjectUrlCount = Math.max(
            maxResidentObjectUrlCount,
            residentAttachmentIds.length
          );
        }
      }

      const residentCountBeforeRelease = residentAttachmentIds.length;
      revokedObjectUrlCount += residentAttachmentIds.length;
      residentAttachmentIds.length = 0;

      return {
        rowCount: rows.length,
        firstId: rows[0]?.id ?? null,
        legacyAttachmentCount,
        imageNodeAttachmentCount,
        createdObjectUrlCount,
        maxResidentObjectUrlCount,
        residentCountBeforeRelease,
        residentCountAfterRelease: residentAttachmentIds.length,
        revokedObjectUrlCount,
        imageByteSizeChecksum
      };
    },
    expected: {
      rowCount: nodeCount,
      firstId: "node-0",
      legacyAttachmentCount: MIXED_IMAGE_ATTACHMENT_COUNT / 2,
      imageNodeAttachmentCount: MIXED_IMAGE_ATTACHMENT_COUNT / 2,
      createdObjectUrlCount: MIXED_IMAGE_ATTACHMENT_COUNT,
      maxResidentObjectUrlCount: MIXED_IMAGE_RESIDENCY_LIMIT,
      residentCountBeforeRelease: MIXED_IMAGE_RESIDENCY_LIMIT,
      residentCountAfterRelease: 0,
      revokedObjectUrlCount: MIXED_IMAGE_ATTACHMENT_COUNT,
      imageByteSizeChecksum: MIXED_IMAGE_ATTACHMENT_COUNT * 4
    }
  };
}

function prepareActiveWorkspaceLoad(nodeCount: number): PreparedWorkload {
  const workspace: NotesWorkspace = { nodes: treeNodes(nodeCount) };
  const emptyState = normalizeWorkspace({ nodes: [] });

  return {
    run: () => {
      const loaded = notesWorkspaceReducer(emptyState, {
        type: "settleQueueWork",
        result: { kind: "authoritative", workspace },
        hasPendingWork: false
      });
      return {
        nodeCount: Object.keys(loaded.nodesById).length,
        rootIds: loaded.rootIds,
        indexedChildCount: Object.values(loaded.childIdsByParent).reduce(
          (total, childIds) => total + childIds.length,
          0
        ),
        status: loaded.status
      };
    },
    expected: {
      nodeCount,
      rootIds: ["node-0"],
      indexedChildCount: nodeCount - 1,
      status: "ready"
    }
  };
}

function prepareTokenization(nodeCount: number): PreparedWorkload {
  const sources: string[] = [];
  let expectedTagCount = 0;
  let expectedTokenCount = 0;
  let expectedEndOffsetChecksum = 0;

  for (let index = 0; index < nodeCount; index += 1) {
    const optionalTags = `${index % 5 === 0 ? " #blocked" : ""}${
      index % 7 === 0 ? " #skip" : ""
    }`;
    const source = `Node ${index} roadmap #project${index % 20} @owner${
      index % 10
    } ${index % 3 === 0 ? "#urgent" : "#routine"}${
      optionalTags
    } due 07/12/2026`;
    const tagCount = 3 + (index % 5 === 0 ? 1 : 0) + (index % 7 === 0 ? 1 : 0);
    sources.push(source);
    expectedTagCount += tagCount;
    expectedTokenCount += tagCount * 2 + 1;
    expectedEndOffsetChecksum += source.length;
  }

  return {
    run: () => {
      let tagCount = 0;
      let tokenCount = 0;
      let endOffsetChecksum = 0;
      for (const source of sources) {
        const tokens = tokenizeNoteText(source);
        tokenCount += tokens.length;
        endOffsetChecksum += tokens.at(-1)?.endUtf16 ?? 0;
        for (const token of tokens) {
          tagCount += token.kind === "tag" ? 1 : 0;
        }
      }
      return { tagCount, tokenCount, endOffsetChecksum };
    },
    expected: {
      tagCount: expectedTagCount,
      tokenCount: expectedTokenCount,
      endOffsetChecksum: expectedEndOffsetChecksum
    }
  };
}

function prepareVisibleRows(nodeCount: number): PreparedWorkload {
  const nodes = treeNodes(nodeCount);
  const depths: number[] = [];
  let expectedDepthChecksum = 0;
  let expectedMaxDepth = 0;

  for (let index = 0; index < nodeCount; index += 1) {
    const parentIndex = index === 0 ? null : Math.floor((index - 1) / 8);
    const depth = parentIndex === null ? 0 : depths[parentIndex]! + 1;
    depths.push(depth);
    expectedDepthChecksum += depth;
    expectedMaxDepth = Math.max(expectedMaxDepth, depth);
  }
  const workspace = normalizeWorkspace({ nodes });

  return {
    run: () => {
      const rows = flattenVisibleOutlineRows(workspace, null);
      let depthChecksum = 0;
      let maxDepth = 0;
      for (const row of rows) {
        depthChecksum += row.depth;
        maxDepth = Math.max(maxDepth, row.depth);
      }
      return {
        rowCount: rows.length,
        depthChecksum,
        maxDepth,
        firstId: rows[0]?.id ?? null
      };
    },
    expected: {
      rowCount: nodeCount,
      depthChecksum: expectedDepthChecksum,
      maxDepth: expectedMaxDepth,
      firstId: "node-0"
    }
  };
}

function prepareTagQueryParser(nodeCount: number): PreparedWorkload {
  const sources: string[] = [];
  let expectedTextLengthChecksum = 0;

  for (let index = 0; index < nodeCount; index += 1) {
    const text = `roadmap${index}`;
    sources.push(
      `${text} #urgent #project${index % 20} OR #project${
        (index + 1) % 20
      } -#blocked`
    );
    expectedTextLengthChecksum += text.length;
  }

  return {
    run: () => {
      let requiredCount = 0;
      let excludedCount = 0;
      let alternativeCount = 0;
      let textLengthChecksum = 0;
      let lastText = "";
      for (const source of sources) {
        const query = parseNoteSearchQuery(source);
        requiredCount += query.requiredTags.length;
        excludedCount += query.excludedTags.length;
        alternativeCount += query.orGroups.reduce(
          (total, group) => total + group.length,
          0
        );
        textLengthChecksum += query.text.length;
        lastText = query.text;
      }
      return {
        parsedQueryCount: sources.length,
        requiredCount,
        excludedCount,
        alternativeCount,
        textLengthChecksum,
        lastText
      };
    },
    expected: {
      parsedQueryCount: nodeCount,
      requiredCount: nodeCount,
      excludedCount: nodeCount,
      alternativeCount: nodeCount * 2,
      textLengthChecksum: expectedTextLengthChecksum,
      lastText: `roadmap${nodeCount - 1}`
    }
  };
}

const dateExpressions = [
  "today",
  "08/15/2026",
  "next week",
  "09/01/2026 - 09/03/2026"
] as const;
const dateStartKeys = [
  "2026-07-12",
  "2026-08-15",
  "2026-07-13",
  "2026-09-01"
] as const;

function prepareDateIndexEntries(nodeCount: number): PreparedWorkload {
  const sources = Array.from(
    { length: nodeCount },
    (_, index) => `Node ${index} schedule ${dateExpressions[index % 4]} #calendar`
  );
  const expectedRangeCount =
    countResidue(nodeCount, 2, 4) + countResidue(nodeCount, 3, 4);

  return {
    run: () => {
      const preparedEntries: string[] = [];
      let rangeCount = 0;
      for (const source of sources) {
        const matches = findNoteDateMatches(source, {
          today: { year: 2026, month: 7, day: 12 },
          weekStartsOn: "monday"
        });
        for (const match of matches) {
          const start = formatLocalDateIso(match.start);
          const end = match.end === null ? "" : formatLocalDateIso(match.end);
          preparedEntries.push(`${start}:${end}`);
          rangeCount += match.end === null ? 0 : 1;
        }
      }
      return {
        preparedEntryCount: preparedEntries.length,
        rangeCount,
        keyLengthChecksum: preparedEntries.reduce(
          (total, entry) => total + entry.length,
          0
        ),
        uniqueStartCount: new Set(
          preparedEntries.map((entry) => entry.slice(0, 10))
        ).size,
        firstStart: preparedEntries[0]?.slice(0, 10) ?? null,
        lastStart: preparedEntries.at(-1)?.slice(0, 10) ?? null
      };
    },
    expected: {
      preparedEntryCount: nodeCount,
      rangeCount: expectedRangeCount,
      keyLengthChecksum: nodeCount * 11 + expectedRangeCount * 10,
      uniqueStartCount: 4,
      firstStart: dateStartKeys[0],
      lastStart: dateStartKeys[(nodeCount - 1) % 4]
    }
  };
}

function lifecycleNodes(nodeCount: number, archived: boolean): NoteNode[] {
  return Array.from({ length: nodeCount }, (_, index) => {
    const rootIndex = index - index % 10;
    return noteNode(index, index % 10 === 0 ? null : `node-${rootIndex}`, {
      archivedAt: archived ? fixedTimestamp : null,
      archiveRootId: archived ? `node-${rootIndex}` : null
    });
  });
}

function prepareArchiveLifecycle(nodeCount: number): PreparedWorkload {
  const targetRootIndex = Math.floor(nodeCount / 20) * 10;
  const targetRootId = `node-${targetRootIndex}`;
  const fallbackRootId = `node-${targetRootIndex + 10}`;
  const targetIds = new Set(
    Array.from({ length: 10 }, (_, offset) => `node-${targetRootIndex + offset}`)
  );
  const activeNodes = lifecycleNodes(nodeCount, false);
  const archivedNodes = lifecycleNodes(nodeCount, true);
  const activeAfterNodes = activeNodes.filter((node) => !targetIds.has(node.id));
  const archiveAfterNodes = archivedNodes.filter(
    (node) => !targetIds.has(node.id)
  );

  const navigation = (scope: "active" | "archive") => ({
    selectedId: `node-${targetRootIndex + 1}`,
    zoomRootId: targetRootId,
    editingNoteId: `node-${targetRootIndex + 1}`,
    pendingFocusId: `node-${targetRootIndex + 1}`,
    pendingFocusField: "title" as const,
    locallyExpandedNodeIds: new Set([targetRootId]),
    scope: { kind: scope } as const
  });

  return {
    run: () => {
      const activeBefore = normalizeWorkspace({ nodes: activeNodes });
      const activeAfter = normalizeWorkspace({ nodes: activeAfterNodes });
      const archiveTransition = resolveRootLifecycleNavigation(
        activeBefore,
        activeAfter,
        targetRootId,
        navigation("active")
      );
      const archiveBefore = normalizeWorkspace({ nodes: archivedNodes });
      const archiveAfter = normalizeWorkspace({ nodes: archiveAfterNodes });
      const unarchiveTransition = resolveRootLifecycleNavigation(
        archiveBefore,
        archiveAfter,
        targetRootId,
        navigation("archive")
      );
      return {
        archiveRemainingNodes: Object.keys(activeAfter.nodesById).length,
        archiveFallbackId: archiveTransition.after.selectedId,
        archiveScope: archiveTransition.after.scope.kind,
        archiveExpansionCount:
          archiveTransition.after.locallyExpandedNodeIds.size,
        unarchiveRemainingNodes: Object.keys(archiveAfter.nodesById).length,
        unarchiveFallbackId: unarchiveTransition.after.selectedId,
        unarchiveScope: unarchiveTransition.after.scope.kind,
        unarchiveExpansionCount:
          unarchiveTransition.after.locallyExpandedNodeIds.size
      };
    },
    expected: {
      archiveRemainingNodes: nodeCount - 10,
      archiveFallbackId: fallbackRootId,
      archiveScope: "active",
      archiveExpansionCount: 0,
      unarchiveRemainingNodes: nodeCount - 10,
      unarchiveFallbackId: fallbackRootId,
      unarchiveScope: "archive",
      unarchiveExpansionCount: 0
    }
  };
}

function prepareMutationUndo(nodeCount: number): PreparedWorkload {
  const originalNodes = treeNodes(nodeCount);
  const targetId = `node-${nodeCount - 1}`;
  const mutatedTitle = `Mutated ${nodeCount - 1}`;
  const mutatedNodes = originalNodes.map((node) =>
    node.id === targetId
      ? { ...node, title: mutatedTitle, isStarred: true }
      : node
  );
  const initial = notesWorkspaceReducer(
    normalizeWorkspace({ nodes: originalNodes }),
    {
      type: "setUiState",
      selectedId: targetId,
      zoomRootId: "node-0",
      editingNoteId: targetId,
      pendingFocusId: targetId,
      pendingFocusField: "title"
    }
  );

  return {
    run: () => {
      const mutated = notesWorkspaceReducer(initial, {
        type: "settleQueueWork",
        result: {
          kind: "authoritative",
          workspace: { nodes: mutatedNodes }
        },
        hasPendingWork: false
      });
      const undone = notesWorkspaceReducer(mutated, {
        type: "settleQueueWork",
        result: {
          kind: "authoritative",
          workspace: { nodes: originalNodes }
        },
        hasPendingWork: false
      });
      return {
        nodeCount: Object.keys(undone.nodesById).length,
        mutatedTitle: mutated.nodesById[targetId]?.title ?? null,
        mutatedStarred: mutated.nodesById[targetId]?.isStarred ?? null,
        undoneTitle: undone.nodesById[targetId]?.title ?? null,
        undoneStarred: undone.nodesById[targetId]?.isStarred ?? null,
        selectedId: undone.selectedId,
        pendingFocusId: undone.pendingFocusId,
        status: undone.status
      };
    },
    expected: {
      nodeCount,
      mutatedTitle,
      mutatedStarred: true,
      undoneTitle: `Node ${nodeCount - 1}`,
      undoneStarred: false,
      selectedId: targetId,
      pendingFocusId: targetId,
      status: "ready"
    }
  };
}

function historySnapshot(selectedId: string): NotesHistorySnapshot {
  return {
    scope: { kind: "active" },
    selectedId,
    zoomRootId: selectedId,
    locallyExpandedNodeIds: [selectedId],
    focus: { nodeId: selectedId, field: "title" }
  };
}

function prepareHistory(nodeCount: number): PreparedWorkload {
  return {
    run: () => {
      let idSequence = 0;
      const history = createNotesHistorySession({
        createId: () => `perf-${idSequence++}`,
        maxSnapshots: HISTORY_SNAPSHOT_LIMIT
      });
      let lastEntryId = "";
      for (let index = 0; index < nodeCount; index += 1) {
        const entry = history.beginStructuralEntry(
          index % 2 === 0 ? "move" : "archive",
          historySnapshot(`before-${index}`)
        );
        history.rememberAfter(entry.entryId, historySnapshot(`after-${index}`));
        lastEntryId = entry.entryId;
      }
      const replay = history.snapshotForReplay(lastEntryId, "redo");
      return {
        sessionId: history.sessionId,
        lastEntryId,
        snapshotCount: history.snapshotCount(),
        replaySelectedId: replay?.selectedId ?? null,
        replayFocusField: replay?.focus?.field ?? null
      };
    },
    expected: {
      sessionId: "perf-0",
      lastEntryId: `perf-${nodeCount}`,
      snapshotCount: Math.min(nodeCount, HISTORY_SNAPSHOT_LIMIT),
      replaySelectedId: `after-${nodeCount - 1}`,
      replayFocusField: "title"
    }
  };
}

const productionScope = "exported production pure frontend path";
const preparationScope =
  "frontend preparation only; backend native search is measured separately";
const projectionBenchmarkScope =
  "synthetic pure projection bookkeeping; not production rendering or residency";

const cases: readonly PerformanceCase[] = [
  {
    label: "active workspace load",
    scope: productionScope,
    nodeCount: 1_000,
    operationsPerSample: 50,
    recordedBaseline: recordedBaseline(0.017341),
    prepare: prepareActiveWorkspaceLoad
  },
  {
    label: "active workspace load",
    scope: productionScope,
    nodeCount: 10_000,
    operationsPerSample: 10,
    recordedBaseline: recordedBaseline(0.281828),
    prepare: prepareActiveWorkspaceLoad
  },
  {
    label: "tokenization",
    scope: productionScope,
    nodeCount: 1_000,
    operationsPerSample: 10,
    recordedBaseline: recordedBaseline(0.257646),
    prepare: prepareTokenization
  },
  {
    label: "tokenization",
    scope: productionScope,
    nodeCount: 10_000,
    operationsPerSample: 2,
    recordedBaseline: recordedBaseline(2.616723),
    prepare: prepareTokenization
  },
  {
    label: "visible-row derivation",
    scope: productionScope,
    nodeCount: 1_000,
    operationsPerSample: 200,
    recordedBaseline: recordedBaseline(0.017812),
    prepare: prepareVisibleRows
  },
  {
    label: "visible-row derivation",
    scope: productionScope,
    nodeCount: 10_000,
    operationsPerSample: 20,
    recordedBaseline: recordedBaseline(0.217552),
    prepare: prepareVisibleRows
  },
  {
    label: "mixed image outline projection bookkeeping",
    scope: projectionBenchmarkScope,
    nodeCount: 10_000,
    operationsPerSample: 20,
    recordedBaseline: recordedBaseline(0.299916),
    prepare: prepareMixedImageOutlineProjectionBookkeeping
  },
  {
    label: "tag query parser preparation",
    scope: preparationScope,
    nodeCount: 1_000,
    operationsPerSample: 3,
    recordedBaseline: recordedBaseline(0.536371),
    prepare: prepareTagQueryParser
  },
  {
    label: "tag query parser preparation",
    scope: preparationScope,
    nodeCount: 10_000,
    operationsPerSample: 2,
    recordedBaseline: recordedBaseline(5.336507),
    prepare: prepareTagQueryParser
  },
  {
    label: "date token parse + index preparation",
    scope: preparationScope,
    nodeCount: 1_000,
    operationsPerSample: 4,
    recordedBaseline: recordedBaseline(0.380369),
    prepare: prepareDateIndexEntries
  },
  {
    label: "date token parse + index preparation",
    scope: preparationScope,
    nodeCount: 10_000,
    operationsPerSample: 2,
    recordedBaseline: recordedBaseline(3.809282),
    prepare: prepareDateIndexEntries
  },
  {
    label: "Archive/unarchive lifecycle preparation",
    scope: productionScope,
    nodeCount: 1_000,
    operationsPerSample: 20,
    recordedBaseline: recordedBaseline(0.061359),
    prepare: prepareArchiveLifecycle
  },
  {
    label: "Archive/unarchive lifecycle preparation",
    scope: productionScope,
    nodeCount: 10_000,
    operationsPerSample: 5,
    recordedBaseline: recordedBaseline(0.950349),
    prepare: prepareArchiveLifecycle
  },
  {
    label: "mutation + Undo workspace settlement",
    scope: productionScope,
    nodeCount: 1_000,
    operationsPerSample: 30,
    recordedBaseline: recordedBaseline(0.030063),
    prepare: prepareMutationUndo
  },
  {
    label: "mutation + Undo workspace settlement",
    scope: productionScope,
    nodeCount: 10_000,
    operationsPerSample: 3,
    recordedBaseline: recordedBaseline(0.439334),
    prepare: prepareMutationUndo
  },
  {
    label: "local history eviction",
    scope: productionScope,
    nodeCount: 1_000,
    operationsPerSample: 10,
    recordedBaseline: recordedBaseline(0.093432),
    prepare: prepareHistory
  },
  {
    label: "local history eviction",
    scope: productionScope,
    nodeCount: 10_000,
    operationsPerSample: 2,
    recordedBaseline: recordedBaseline(1.004093),
    prepare: prepareHistory
  }
];

performanceSuite("notes expansion frontend performance", () => {
  beforeAll(() => {
    console.info(
      "[notes-perf] invocation: NOTES_PERF=1 npm test -- " +
        "src/features/notes/notesExpansion.performance.test.ts " +
        "--pool=threads --maxWorkers=1 --no-file-parallelism"
    );
    console.info(
      `[notes-perf] recorded=${JSON.stringify(recordedEnvironment)}`
    );
  });

  it("declares the exact reviewed workload-size matrix", () => {
    const sizesByLabel = new Map<string, number[]>();
    for (const performanceCase of cases) {
      const sizes = sizesByLabel.get(performanceCase.label) ?? [];
      sizes.push(performanceCase.nodeCount);
      sizesByLabel.set(performanceCase.label, sizes);
    }

    expect(Object.fromEntries(sizesByLabel)).toEqual({
      "active workspace load": [1_000, 10_000],
      tokenization: [1_000, 10_000],
      "visible-row derivation": [1_000, 10_000],
      "mixed image outline projection bookkeeping": [10_000],
      "tag query parser preparation": [1_000, 10_000],
      "date token parse + index preparation": [1_000, 10_000],
      "Archive/unarchive lifecycle preparation": [1_000, 10_000],
      "mutation + Undo workspace settlement": [1_000, 10_000],
      "local history eviction": [1_000, 10_000]
    });
  });

  it("scopes the mixed image projection benchmark as synthetic bookkeeping", () => {
    const mixedImageCase = cases.find(
      ({ label }) => label === "mixed image outline projection bookkeeping"
    );

    expect(mixedImageCase?.scope).toBe(projectionBenchmarkScope);
    expect(mixedImageCase?.scope).toContain(
      "not production rendering or residency"
    );
    expect(
      cases.some(({ label }) => /mixed image.*residency/iu.test(label))
    ).toBe(false);
  });

  it("labels backend-owned search work as frontend preparation only", () => {
    expect(cases.map(({ label }) => label)).toContain(
      "tag query parser preparation"
    );
    expect(cases.map(({ label }) => label)).toContain(
      "date token parse + index preparation"
    );
    expect(cases.some(({ label }) => /tag.*match|production search/iu.test(label)))
      .toBe(false);
    expect(
      cases
        .filter(({ label }) => /tag|date/iu.test(label))
        .every(({ scope }) => scope === preparationScope)
    ).toBe(true);
  });

  it("stores only the recorded median of three pair ratios", () => {
    for (const performanceCase of cases) {
      expect(Object.keys(performanceCase.recordedBaseline)).toEqual([
        "pairedRatioMedian"
      ]);
      expect(
        performanceCase.recordedBaseline.pairedRatioMedian
      ).toBeGreaterThan(0);
    }
  });

  it("records like-for-like paired normalization without changing the gate", () => {
    expect(recordedEnvironment.sampling).toContain("3 measured paired batches");
    expect(recordedEnvironment.sampling).toContain("per case");
    expect(recordedEnvironment.sampling).toContain("median of 3 pair ratios");
    expect(recordedEnvironment.sampling).toContain(
      "outputs validated only after both timing windows"
    );
    expect(recordedEnvironment.sampling).not.toContain("p95");
    expect(WARMUP_PAIR_COUNT).toBe(3);
    expect(MEASURED_PAIR_COUNT).toBe(3);
    expect(REGRESSION_LIMIT).toBe(1.2);
  });

  it("rejects one localized scheduler spike without hiding a sustained slowdown", () => {
    const baseline = recordedBaseline(1);
    const schedulerSpike = representativePairedSample([
      { workloadMs: 1, calibrationMs: 1 },
      { workloadMs: 9, calibrationMs: 1 },
      { workloadMs: 1.01, calibrationMs: 1 }
    ]);
    const sustainedSlowdown = representativePairedSample([
      { workloadMs: 1.21, calibrationMs: 1 },
      { workloadMs: 1.22, calibrationMs: 1 },
      { workloadMs: 1.23, calibrationMs: 1 }
    ]);

    expect(schedulerSpike.normalizedRatio).toBe(1.01);
    expect(
      normalizedRegressionRatio(schedulerSpike.normalizedRatio, baseline)
    ).toBeLessThanOrEqual(REGRESSION_LIMIT);
    expect(sustainedSlowdown.normalizedRatio).toBe(1.22);
    expect(
      normalizedRegressionRatio(sustainedSlowdown.normalizedRatio, baseline)
    ).toBeGreaterThan(REGRESSION_LIMIT);
  });

  it("normalizes a common two-times host slowdown within each pair", () => {
    const baseline = recordedBaseline(1);
    const current = representativePairedSample([
      { workloadMs: 2, calibrationMs: 2 },
      { workloadMs: 2.02, calibrationMs: 2 },
      { workloadMs: 2.04, calibrationMs: 2 }
    ]);

    expect(current.normalizedRatio).toBeCloseTo(1.01, 10);
    expect(normalizedRegressionRatio(current.normalizedRatio, baseline)).toBeCloseTo(
      1.01,
      10
    );
  });

  it.each([
    { workloadFirst: true, expectedRuns: ["run:workload", "run:calibration"] },
    { workloadFirst: false, expectedRuns: ["run:calibration", "run:workload"] }
  ])(
    "validates both outputs after adjacent timing windows when workloadFirst=$workloadFirst",
    ({ workloadFirst, expectedRuns }) => {
      const events: string[] = [];
      const observableWorkload = (label: string): PreparedWorkload => ({
        run: () => {
          events.push(`run:${label}`);
          return Object.defineProperty({}, "value", {
            enumerable: true,
            get: () => {
              events.push(`validate:${label}`);
              return label;
            }
          });
        },
        expected: { value: label }
      });

      measurePairedBatch(
        observableWorkload("calibration"),
        observableWorkload("workload"),
        1,
        workloadFirst
      );

      const firstValidationIndex = events.findIndex((event) =>
        event.startsWith("validate:")
      );
      expect(events.slice(0, firstValidationIndex)).toEqual(expectedRuns);
    }
  );

  it("runs pure timing in Node without a DOM environment", () => {
    expect(process.release.name).toBe("node");
    expect(typeof document).toBe("undefined");
  });

  it.each(cases)(
    "$label: $nodeCount nodes; paired-ratio median <= recorded +20%",
    { timeout: 120_000 },
    ({
      label,
      scope,
      nodeCount,
      operationsPerSample,
      recordedBaseline: baseline,
      prepare
    }) => {
      const pairedStats = measurePairedWorkload(
        prepare(nodeCount),
        operationsPerSample
      );
      const stats = pairedStats.workload;
      const localCalibration = pairedStats.calibration;
      const pairedRatios = pairedStats.normalized;
      const ratio = normalizedRegressionRatio(
        pairedRatios.medianMs,
        baseline
      );

      expect(stats.samplesMs).toHaveLength(MEASURED_PAIR_COUNT);
      expect(stats.samplesMs.every(Number.isFinite)).toBe(true);
      expect(localCalibration.samplesMs).toHaveLength(MEASURED_PAIR_COUNT);
      expect(localCalibration.samplesMs.every(Number.isFinite)).toBe(true);
      expect(pairedRatios.samplesMs).toHaveLength(MEASURED_PAIR_COUNT);
      expect(pairedRatios.samplesMs.every(Number.isFinite)).toBe(true);
      console.info(
        `[notes-perf] ${label}; scope=${scope}; nodes=${nodeCount}; ` +
          `pairedWarmups=${WARMUP_PAIR_COUNT}; ` +
          `measuredPairs=${MEASURED_PAIR_COUNT}; ` +
          `operationsPerSample=${operationsPerSample}; ` +
          `workloadMedian=${stats.medianMs.toFixed(2)}ms; ` +
          `calibrationMedian=${localCalibration.medianMs.toFixed(
            2
          )}ms; pairedRatioMedian=${pairedRatios.medianMs.toFixed(6)}; ` +
          `recordedPairedRatioMedian=${baseline.pairedRatioMedian.toFixed(
            6
          )}; ` +
          `normalizedRatio=${ratio.toFixed(3)}; gate=${REGRESSION_LIMIT.toFixed(
            2
          )}`
      );
      expect(ratio).toBeLessThanOrEqual(REGRESSION_LIMIT);
    }
  );
});
